### ISSUE TITLE
build error in nvidia-xavier

### ISSUE THREAD

**Issue by sandip761** [mlcommons/inference_results_v0.7#12]
In file included from /usr/local/DALI/dali/image/tiff_libtiff.cc:61:0:
/usr/local/DALI/dali/image/tiff_libtiff.h:18:10: fatal error: tiffio.h: No such file or directory
 #include <tiffio.h>

**Comment by psyhtest** [comment]
Hi @sandip761, I've also hit this issue and solved it by patching the installation script as follows:

<pre><font color="#859900"><b>anton@xavier</b></font>:<font color="#268BD2"><b>/datasets/inference_results_v0.7/closed/NVIDIA</b></font>$ git diff scripts/install_xavier_dependencies.sh
<b>diff --git a/closed/NVIDIA/scripts/install_xavier_dependencies.sh b/closed/NVIDIA/scripts/install_xavier_dependencies.sh</b>
<b>old mode 100644</b>
<b>new mode 100755</b>
<b>index 07f5777b..cca38ba0</b>
<b>--- a/closed/NVIDIA/scripts/install_xavier_dependencies.sh</b>
<b>+++ b/closed/NVIDIA/scripts/install_xavier_dependencies.sh</b>
<font color="#2AA198">@@ -19,7 +19,7 @@</font> sudo apt-get install -y virtualenv
 sudo apt-get install -y cmake pkg-config zip g++ unzip zlib1g-dev
 sudo apt-get install -y --no-install-recommends clang libglib2.0-dev
 sudo apt-get install -y libhdf5-serial-dev hdf5-tools
<font color="#DC322F">-sudo apt-get install -y zlib1g-dev zip libjpeg8-dev libhdf5-dev</font>
<font color="#859900">+sudo apt-get install -y zlib1g-dev zip libjpeg8-dev libhdf5-dev libtiff5-dev</font>
 
 # matplotlib dependencies
 sudo apt-get install -y libssl-dev libfreetype6-dev libpng-dev
</pre>

Unfortunately, the script is non-reenterable: you should manually delete `/usr/local/DALI` first, and only then restart the script from the beginning. (Yes, building Python packages from source takes ages.)

**Comment by nvpohanh** [comment]
Thanks for the patch! we have applied the patch to our v1.0 submission codes, too.
