### ISSUE TITLE
Reproducing NVIDIA's Xavier submission with JetPack 4.5

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/inference_results_v0.7#15]
JetPack 4.5 is the latest production release to which one can upgrade without reflashing the board with [20.09 Jetson CUDA-X AI Developer Preview](https://developer.nvidia.com/embedded/20.09-Jetson-CUDA-X-AI-Developer-Preview) that NVIDIA used for their v0.7 submission. Although released several (4-5?) months after the v0.7 submission, it still lags behind in terms of the TensorRT version: v7.1.3 vs v7.2.0. This may explain the issues I'm seeing when trying to build the test harness:

<pre>
<font color="#859900"><b>anton@xavier</b></font>:<font color="#268BD2"><b>/datasets/inference_results_v0.7/closed/NVIDIA</b></font>$ make build                                                                                                                                    
Cloning Official MLPerf Inference (For Loadgen Files)                                                                          
Cloning into &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/inference&apos;...
<...>
-- Configuring done           
-- Generating done                                          
-- Build files have been written to: /datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin
make[2]: Entering directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
make[3]: Entering directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
make[4]: Entering directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
<font color="#D33682"><b>Scanning dependencies of target instancenorm3dplugin</b></font>
make[4]: Leaving directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
make[4]: Entering directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
[ 25%] <font color="#859900">Building CUDA object CMakeFiles/instancenorm3dplugin.dir/src/instanceNormalization3DPlugin.cu.o</font>                  
[ 50%] <font color="#859900">Building CUDA object CMakeFiles/instancenorm3dplugin.dir/src/instance_norm_fwd_impl.cu.o</font>
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(249): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kDHWC8&quot;
                        
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(250): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kCDHW32&quot;
                                                          
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(358): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kDHWC8&quot;
                                                                  
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(359): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kCDHW32&quot;
                                                      
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(455): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kDHWC8&quot;
                                                                             
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(460): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kCDHW32&quot;
                          
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(465): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kCDHW32&quot;
                                                                                                       
/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(466): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kCDHW32&quot;

/datasets/inference_results_v0.7/closed/NVIDIA/code/plugin/instanceNormalization3DPlugin/src/instanceNormalization3DPlugin.cu(468): error: enum &quot;nvinfer1::TensorFormat&quot; has no member &quot;kCDHW32&quot;

9 errors detected in the compilation of &quot;/tmp/tmpxft_0000318e_00000000-8_instanceNormalization3DPlugin.compute_75.cpp1.ii&quot;.
CMakeFiles/instancenorm3dplugin.dir/build.make:82: recipe for target &apos;CMakeFiles/instancenorm3dplugin.dir/src/instanceNormalization3DPlugin.cu.o&apos; failed
make[4]: *** [CMakeFiles/instancenorm3dplugin.dir/src/instanceNormalization3DPlugin.cu.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
CMakeFiles/Makefile2:95: recipe for target &apos;CMakeFiles/instancenorm3dplugin.dir/all&apos; failed
make[3]: *** [CMakeFiles/instancenorm3dplugin.dir/all] Error 2
make[3]: Leaving directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
Makefile:103: recipe for target &apos;all&apos; failed
make[2]: *** [all] Error 2
make[2]: Leaving directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA/build/plugins/instanceNormalization3DPlugin&apos;
Makefile:305: recipe for target &apos;build_plugins&apos; failed
make[1]: *** [build_plugins] Error 2
make[1]: Leaving directory &apos;/datasets/inference_results_v0.7/closed/NVIDIA&apos;
Makefile:247: recipe for target &apos;build&apos; failed
make: *** [build] Error 2
</pre>

@nvpohanh Can you perhaps suggest a workaround? `instanceNormalization3DPlugin` sounds like something related to 3D U-net, which I don't need at the moment. Perhaps I can bypass building this plugin?

**Comment by psyhtest** [comment]
I managed to build without errors by disabling `instanceNormalization3DPlugin` and `pixelShuffle3DPlugin`:

<pre>
<font color="#859900"><b>anton@xavier</b></font>:<font color="#268BD2"><b>/datasets/inference_results_v0.7/closed/NVIDIA</b></font>$ git diff Makefile
<b>diff --git a/closed/NVIDIA/Makefile b/closed/NVIDIA/Makefile</b>
<b>index 4679ec29..3961fb96 100644</b>
<b>--- a/closed/NVIDIA/Makefile</b>
<b>+++ b/closed/NVIDIA/Makefile</b>
<font color="#2AA198">@@ -320,6 +320,7 @@</font> endif
        cd build/plugins/RNNTOptPlugin \
                &amp;&amp; cmake -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) $(PROJECT_ROOT)/code/plugin/RNNTOptPlugin \
                &amp;&amp; make -j
<font color="#859900">+ifeq ($(ARCH), x86_64)</font>
        mkdir -p build/plugins/instanceNormalization3DPlugin
        cd build/plugins/instanceNormalization3DPlugin \
                &amp;&amp; cmake -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) $(PROJECT_ROOT)/code/plugin/instanceNormalization3DPlugin \
<font color="#2AA198">@@ -328,6 +329,7 @@</font> endif
        cd build/plugins/pixelShuffle3DPlugin \
                &amp;&amp; cmake -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) $(PROJECT_ROOT)/code/plugin/pixelShuffle3DPlugin \
                &amp;&amp; make -j
<font color="#859900">+endif</font>
 
 # Build LoadGen.
 .PHONY: build_loadgen
</pre>

and removing two (new?) tensor format cases:
<pre>
<font color="#859900"><b>anton@xavier</b></font>:<font color="#268BD2"><b>/datasets/inference_results_v0.7/closed/NVIDIA</b></font>$ git diff code/harness/lwis/include/lwis_buffers.h
git diff code/harness/lwis/include/lwis_buffers.h
<b>diff --git a/closed/NVIDIA/code/harness/lwis/include/lwis_buffers.h b/closed/NVIDIA/code/harness/lwis/include/lwis_buffers.h</b>
<b>index 5a79260c..59f8c120 100644</b>
<b>--- a/closed/NVIDIA/code/harness/lwis/include/lwis_buffers.h</b>
<b>+++ b/closed/NVIDIA/code/harness/lwis/include/lwis_buffers.h</b>
<font color="#2AA198">@@ -80,10 +80,8 @@</font> inline int64_t volume(const nvinfer1::Dims&amp; d, const nvinfer1::TensorFormat&amp; for
         case nvinfer1::TensorFormat::kCHW2: spv = 2; channelDim = d_new.nbDims - 3; break;
         case nvinfer1::TensorFormat::kCHW4: spv = 4; channelDim = d_new.nbDims - 3; break;
         case nvinfer1::TensorFormat::kHWC8: spv = 8; channelDim = d_new.nbDims - 3; break;
<font color="#DC322F">-        case nvinfer1::TensorFormat::kDHWC8: spv = 8; channelDim = d_new.nbDims - 4; break;</font>
         case nvinfer1::TensorFormat::kCHW16: spv = 16; channelDim = d_new.nbDims - 3; break;
         case nvinfer1::TensorFormat::kCHW32: spv = 32; channelDim = d_new.nbDims - 3; break;
<font color="#DC322F">-        case nvinfer1::TensorFormat::kCDHW32: spv = 32; channelDim = d_new.nbDims - 4; break;</font>
         case nvinfer1::TensorFormat::kLINEAR:
         default: spv = 1; channelDim = -1; break;
     }
</pre>

**Comment by nvpohanh** [comment]
@psyhtest Our submission codes don't support TRT 7.1 at all. TRT 7.2.0 is the minimal requirement, but I know that TRT 7.2.0 probably doesn't work with JP4.5. Could you try TRT 7.2.2 instead? https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html#rel_7-2-2

**Comment by psyhtest** [comment]
@nvpohanh I don't think one can upgrade TensorRT on Jetson boards that easily? It seems I either needs to install the Developer Preview release, or wait until JetPack 4.6 or even later.

Actually, because of using a Developer Preview release, should not the Xavier v0.7 submission have been categorised as "Preview"? According to the [MLPerf Inference rules](https://github.com/mlcommons/inference_policies/blob/master/inference_rules.adoc#system-and-framework-must-be-available):

> If you are measuring the performance of a publicly available and widely-used system or framework, you must use publicly available and widely-used versions of the system or framework.

While Xavier is publicly available and widely-used, a Developer Preview may be publicly available but is not widely-used.

**Comment by nvpohanh** [comment]
@DilipSequeira Could you provide more detailed explanation?

We used [20.09 Jetson CUDA-X AI](https://developer.nvidia.com/embedded/20.09-Jetson-CUDA-X-AI-Developer-Preview) for our Xavier v0.7 submissions. As the descriptions suggest, it is for whoever is interested in trying latest CUDA-X AI components and is available to everyone to deploy on their systems.

As for v1.0, if you are interested in using a newer software stack than the one we used in v0.7 for v1.0 Xavier submission, could you send an email to me and Dilip so that we can discuss there?

**Comment by psyhtest** [comment]
@nvpohanh Sure, will do, thanks.

**Comment by DilipSequeira** [comment]
Hi Anton

The specific definition of _Available_ for the purpose of submission categories is set out in section 7.3.1 of the general [policies document](https://github.com/mlcommons/policies/blob/master/submission_rules.adoc).

_For binaries, the binary must be made available as release, or as a "beta" release with the requirement that optimizations will be included in a future "official" release._ 

There is some inconsistency between this section and the statement you point out in the inference rules.

**Comment by psyhtest** [comment]
The vision benchmarks seem to work with TensorRT v7.1.3, so closing.
