### ISSUE TITLE
What is the DLRM diagram like?

### ISSUE THREAD

**Issue by warren-lei** [mlcommons/inference_results_v0.7#16]
The dlrm is  a *.pb model or *onnx model?

Can I get the model visualization diagram?

**Comment by nvpohanh** [comment]
@warren-lei You can find the link to the ONNX file here: https://github.com/mlcommons/inference/tree/master/recommendation/dlrm/pytorch

**Comment by warren-lei** [comment]
> @warren-lei You can find the link to the ONNX file here: https://github.com/mlcommons/inference/tree/master/recommendation/dlrm/pytorch

Thanks
