### ISSUE TITLE
Didn't find the submission folder for Qualcomm, will it be updated recently or they didn't release one? 

### ISSUE THREAD

**Issue by swb1234554321** [mlcommons/inference_results_v0.7#2]
I do find that Qualcomm submitted their inference v0.7 results on several networks, but I couldn't find the apropriate github folder. Can you please give a pointer to their submission? Thx!

**Comment by psyhtest** [comment]
This repository only includes submissions for the Datacenter and Edge categories. I don't know if there is a similar repository for Mobile.

@TheKanter @jveejay
