### ISSUE TITLE
[NVIDIA] ImageNet preprocessing fails

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/inference_results_v0.7#8]
Can't figure out which image libraries are needed for ImageNet preprocessing on a new Ubuntu 20.04.1 image:

```bash
$ cd ~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA
$ bash code/resnet50/tensorrt/download_data.sh
Dataset for ResNet50 already exists!

$ sudo apt install libopencv-dev
$ python3 -m pip install opencv-python

$ python3 code/resnet50/tensorrt/preprocess_data.py
[2020-11-05 16:11:08,877 preprocess_data.py:108 INFO] Loading and preprocessing images. This might take a while...
[2020-11-05 16:11:08,877 image_preprocessor.py:79 INFO] Processing image No.0/500...
Traceback (most recent call last):
  File "code/resnet50/tensorrt/preprocess_data.py", line 116, in <module>
    main()
  File "code/resnet50/tensorrt/preprocess_data.py", line 111, in main
    preprocess_imagenet_for_resnet50(data_dir, preprocessed_data_dir, formats, overwrite, cal_only, val_only)
  File "code/resnet50/tensorrt/preprocess_data.py", line 48, in preprocess_imagenet_for_resnet50
    preprocessor.run(os.path.join(data_dir, "imagenet"), os.path.join(preprocessed_data_dir, "imagenet", "ResNet50"),
  File "/home/anton/projects/mlperf/submissions_inference_0_7/closed/NVIDIA/code/common/image_preprocessor.py", line 69, in run
    self.convert(image_list)
  File "/home/anton/projects/mlperf/submissions_inference_0_7/closed/NVIDIA/code/common/image_preprocessor.py", line 86, in convert
    image_fp32 = self.loader(os.path.join(self.src_dir, img_file))
  File "code/resnet50/tensorrt/preprocess_data.py", line 32, in loader
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-99ib2vsi/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

@nvpohanh Any ideas?

**Comment by psyhtest** [comment]
Ah, it's not a library dependency as I thought.

Despite two environment variables being defined:
```
anton@krai:~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA$ echo $MLPERF_SCRATCH_PATH 
/data/mlperf-scratch-path
anton@krai:~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA$ echo $DATA_DIR
/data/mlperf-scratch-path/data
```
the script tries to open `build/data/imagenet/ILSVRC2012_val_00027145.JPEG` and fails.

**Comment by psyhtest** [comment]
This seems to work:

```bash
$ python3 code/resnet50/tensorrt/preprocess_data.py \
--data_dir=$MLPERF_SCRATCH_PATH/data --preprocessed_data_dir=$MLPERF_SCRATCH_PATH/preprocessed_data
```

So it's just a case of [incomplete instructions](https://github.com/mlperf/inference_results_v0.7/tree/master/closed/NVIDIA/code/resnet50/tensorrt#preprocessing-the-dataset-for-usage).

It would also be good to document dependencies on OpenCV:

```bash
$ sudo apt install libopencv-dev
$ python3 -m pip install opencv-python
```

**Comment by nvpohanh** [comment]
> It would also be good to document dependencies on OpenCV:

@psyhtest Does it fail if you run it in our container?

**Comment by psyhtest** [comment]
@nvpohanh It didn't appear that the [instructions](https://github.com/mlperf/inference_results_v0.7/tree/master/closed/NVIDIA/code/resnet50/tensorrt#preprocessing-the-dataset-for-usage) were intended to be run using the image. However, I've just tried the following:

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA</b></font>$ docker run -dt -e NVIDIA_VISIBLE_DEVICES=ALL -w /work \
&gt;     --security-opt apparmor=unconfined --security-opt seccomp=unconfined \
&gt;     -v $HOME:/mnt$HOME \
&gt;     -v $PWD:/work \
&gt;     -v $MLPERF_SCRATCH_PATH:$MLPERF_SCRATCH_PATH \
&gt;     -e MLPERF_SCRATCH_PATH=$MLPERF_SCRATCH_PATH \
&gt;     --name mlperf-inference-anton mlperf-inference:anton-latest
b1fd74b05def78477fb4d1f962b3ce6373e5c79c327f743920ee6026f09f7819
</pre>

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA</b></font>$ docker exec mlperf-inference-anton bash -c &apos;python3 code/resnet50/tensorrt/preprocess_data.py&apos;
[2020-11-10 14:34:14,266 preprocess_data.py:108 INFO] Loading and preprocessing images. This might take a while...
[2020-11-10 14:34:14,266 image_preprocessor.py:79 INFO] Processing image No.0/500...
Traceback (most recent call last):
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 116, in &lt;module&gt;
    main()
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 111, in main
    preprocess_imagenet_for_resnet50(data_dir, preprocessed_data_dir, formats, overwrite, cal_only, val_only)
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 49, in preprocess_imagenet_for_resnet50
    &quot;data_maps/imagenet/cal_map.txt&quot;, [&quot;fp32&quot;], overwrite)
  File &quot;/work/code/common/image_preprocessor.py&quot;, line 69, in run
    self.convert(image_list)
  File &quot;/work/code/common/image_preprocessor.py&quot;, line 86, in convert
    image_fp32 = self.loader(os.path.join(self.src_dir, img_file))
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 32, in loader
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-hw4jq8lf/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function &apos;cvtColor&apos;
</pre>

**Comment by psyhtest** [comment]
Alas, explicitly providing the paths does not help either:

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA</b></font>$ docker exec mlperf-inference-anton bash -c &apos;python3 code/resnet50/tensorrt/preprocess_data.py \
--data_dir=$MLPERF_SCRATCH_PATH/data --preprocessed_data_dir=$MLPERF_SCRATCH_PATH/preprocessed_data&apos;
[2020-11-10 14:41:55,922 preprocess_data.py:108 INFO] Loading and preprocessing images. This might take a while...
[2020-11-10 14:41:55,923 image_preprocessor.py:79 INFO] Processing image No.0/500...
Traceback (most recent call last):
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 116, in &lt;module&gt;
    main()
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 111, in main
    preprocess_imagenet_for_resnet50(data_dir, preprocessed_data_dir, formats, overwrite, cal_only, val_only)
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 49, in preprocess_imagenet_for_resnet50
    &quot;data_maps/imagenet/cal_map.txt&quot;, [&quot;fp32&quot;], overwrite)
  File &quot;/work/code/common/image_preprocessor.py&quot;, line 69, in run
    self.convert(image_list)
  File &quot;/work/code/common/image_preprocessor.py&quot;, line 86, in convert
    image_fp32 = self.loader(os.path.join(self.src_dir, img_file))
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 32, in loader
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-hw4jq8lf/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function &apos;cvtColor&apos;
</pre>

**Comment by psyhtest** [comment]
The same failure from within the container:

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA</b></font>$ make launch_docker
Launching Docker interactive session
docker run --gpus=all --rm -ti -w /work -v /home/anton/projects/mlperf/submissions_inference_0_7/closed/NVIDIA:/work -v /home/anton:/mnt//home/anton \
        --cap-add SYS_ADMIN -e NVIDIA_MIG_CONFIG_DEVICES=&quot;all&quot; \
        -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro \
        --security-opt apparmor=unconfined --security-opt seccomp=unconfined \
        --name mlperf-inference-anton -h mlperf-inference-anton --add-host mlperf-inference-anton:127.0.0.1 \
        --user 1000:1000 --net host --device /dev/fuse --cap-add SYS_ADMIN -v /data/mlperf-scratch-path:/data/mlperf-scratch-path  \
        -e MLPERF_SCRATCH_PATH=/data/mlperf-scratch-path mlperf-inference:anton
(mlperf) anton@mlperf-inference-anton:/work$ python3 code/resnet50/tensorrt/preprocess_data.py
[2020-11-10 17:56:53,197 preprocess_data.py:108 INFO] Loading and preprocessing images. This might take a while...
[2020-11-10 17:56:53,198 image_preprocessor.py:79 INFO] Processing image No.0/500...
Traceback (most recent call last):
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 116, in &lt;module&gt;
    main()
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 111, in main
    preprocess_imagenet_for_resnet50(data_dir, preprocessed_data_dir, formats, overwrite, cal_only, val_only)
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 49, in preprocess_imagenet_for_resnet50
    &quot;data_maps/imagenet/cal_map.txt&quot;, [&quot;fp32&quot;], overwrite)
  File &quot;/work/code/common/image_preprocessor.py&quot;, line 69, in run
    self.convert(image_list)
  File &quot;/work/code/common/image_preprocessor.py&quot;, line 86, in convert
    image_fp32 = self.loader(os.path.join(self.src_dir, img_file))
  File &quot;code/resnet50/tensorrt/preprocess_data.py&quot;, line 32, in loader
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-hw4jq8lf/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function &apos;cvtColor&apos;

(mlperf) anton@mlperf-inference-anton:/work$ 
</pre>

Am I unlucky or what?

**Comment by psyhtest** [comment]
It eventually worked from within the container as follows:

<pre>(mlperf) anton@mlperf-inference-anton:/work$ python3 code/resnet50/tensorrt/preprocess_data.py \
--data_dir=$MLPERF_SCRATCH_PATH/data --preprocessed_data_dir=$MLPERF_SCRATCH_PATH/preprocessed_data
</pre>

I think the problems above might have been caused by using a symbolic link to ImageNet. Preprocessing from within the container succeeded only when I placed the dataset directly under `$MLPERF_SCRATCH_PATH/data/imagenet`.

**Comment by nvpohanh** [comment]
> I think the problems above might have been caused by using a symbolic link to ImageNet. Preprocessing from within the container succeeded only when I placed the dataset directly under $MLPERF_SCRATCH_PATH/data/imagenet.

Shouldn't this be expected? Where did you put imagenet at? Alternatively, you can add `DOCKER_ARGS="-v <path/to/imagenet>:<path/to/imagenet>"` so that you can "see" that path from within the container.

**Comment by psyhtest** [comment]
> Shouldn't this be expected? 

I blame sleep deprivation for that :). But it wasn't clear whether the preprocessing should have been done from the outside or from the inside of the container first.
