### ISSUE TITLE
[NVIDIA] Low ResNet50 accuracy when recalibrating on an equivalent dataset

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/inference_results_v0.7#9]
I get ResNet50 accuracy=76.064% (good=38032, total=50000) when reproducing NVIDIA's v0.7 submission on a GTX 1650 Ti (with Max-Q design):

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA</b></font>$ export MLPERF_SCRATCH_PATH=/data/mlperf-scratch-path
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed/NVIDIA</b></font>$ make launch_docker
Launching Docker interactive session
docker run --gpus=all --rm -ti -w /work -v /home/anton/projects/mlperf/submissions_inference_0_7/closed/NVIDIA:/work -v /home/anton:/mnt//home/anton \
        --cap-add SYS_ADMIN -e NVIDIA_MIG_CONFIG_DEVICES=&quot;all&quot; \
        -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro \
        --security-opt apparmor=unconfined --security-opt seccomp=unconfined \
        --name mlperf-inference-anton -h mlperf-inference-anton --add-host mlperf-inference-anton:127.0.0.1 \
        --user 1000:1000 --net host --device /dev/fuse --cap-add SYS_ADMIN -v /data/mlperf-scratch-path/:/data/mlperf-scratch-path/  \
        -e MLPERF_SCRATCH_PATH=/data/mlperf-scratch-path/ mlperf-inference:anton
(mlperf) anton@mlperf-inference-anton:/work$ make generate_engines RUN_ARGS="--benchmarks=resnet50 --scenarios=offline" && \
make run_harness RUN_ARGS="--benchmarks=resnet50 --scenarios=offline --test_mode=AccuracyOnly"
...
[2020-11-13 15:14:07,569 builder.py:145 INFO] Building ./build/engines/GTX_1650_Ti_Max-Q/resnet50/Offline/resnet50-Offline-gpu-b128-int8.default.plan
[TensorRT] <b><i>INFO: User provided dynamic ranges for all network tensors. Calibration skipped.</i></b>
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 1 output network tensors.
[2020-11-13 15:16:16,642 main.py:153 INFO] Finished building engines for resnet50 benchmark in Offline scenario.
Time taken to generate engines: 140.72285294532776 seconds
[2020-11-13 15:16:18,098 main.py:692 INFO] Detected System ID: GTX_1650_Ti_Max-Q
[2020-11-13 15:16:18,107 main.py:546 INFO] Using config files: configs/resnet50/Offline/config.json
[2020-11-13 15:16:18,107 __init__.py:283 INFO] Parsing config file configs/resnet50/Offline/config.json ...
[2020-11-13 15:16:18,107 main.py:559 INFO] Processing config "GTX_1650_Ti_Max-Q_resnet50_Offline"
[2020-11-13 15:16:18,107 main.py:294 INFO] Running harness for resnet50 benchmark in Offline scenario...
...
accuracy=76.064%, good=38032, total=50000

======================= Perf harness results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Cannot find performance result. Maybe you are running in AccuracyOnly mode.

======================= Accuracy results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Accuracy = 76.064, Threshold = 75.695. Accuracy test PASSED.
</pre>

**Comment by psyhtest** [comment]
I observe the same accuracy in several submissions from DellEMC and NVIDIA, which is good:

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7/closed</b></font>$ grep good\=38032 * -R
<font color="#D33682">DellEMC/results/DSS8440_QuadroRTX6000x10_TRT/resnet50/Offline/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/DSS8440_QuadroRTX6000x10_TRT/resnet50/Server/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/DSS8440_QuadroRTX8000x10_TRT/resnet50/Offline/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/DSS8440_QuadroRTX8000x10_TRT/resnet50/Server/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/DSS8440_QuadroRTX8000x8_TRT/resnet50/Offline/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/DSS8440_QuadroRTX8000x8_TRT/resnet50/Server/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/C4140_QuadroRTX6000x4_TRT/resnet50/Offline/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/C4140_QuadroRTX6000x4_TRT/resnet50/Server/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/R7525_QuadroRTX8000x3_TRT/resnet50/Offline/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">DellEMC/results/R7525_QuadroRTX8000x3_TRT/resnet50/Server/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">NVIDIA/results/Xavier_NX_TRT/resnet50/SingleStream/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">NVIDIA/results/AGX_Xavier_TRT/resnet50/SingleStream/accuracy/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">NVIDIA/build/logs/2020.11.13-15.16.17/GTX_1650_Ti_Max-Q_TRT/resnet50/Offline/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
<font color="#D33682">NVIDIA/build/logs/2020.11.10-23.12.48/GTX_1650_Ti_Max-Q_TRT/resnet50/Offline/accuracy.txt</font><font color="#2AA198">:</font>accuracy=76.064%, <font color="#DC322F"><b>good=38032</b></font>, total=50000
</pre>

**Comment by psyhtest** [comment]
I was going to report an issue I observed on another system. It's reproducible there, but all seems to be good on the GTX 1650 Ti one... Please bear with me while I'm trying to root-cause it...

**Comment by psyhtest** [comment]
I've managed to reproduce the issue on my laptop's GPU with the following modifications:

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ git diff closed/NVIDIA/code/common/system_list.py
<b>diff --git a/closed/NVIDIA/code/common/system_list.py b/closed/NVIDIA/code/common/system_list.py</b>
<b>index 10079eaa..90e11de4 100644</b>
<b>--- a/closed/NVIDIA/code/common/system_list.py</b>
<b>+++ b/closed/NVIDIA/code/common/system_list.py</b>
<font color="#2AA198">@@ -22,6 +22,7 @@</font> system_list = ([
     (&quot;A100-SXM4x1&quot;, &quot;A100-SXM4-40GB&quot;, 1),
     (&quot;A100-SXM4x1-MIG_1x1g.5gb&quot;, &quot;A100-SXM4-40GB&quot;, 1),
     (&quot;A100-SXM4x8&quot;, &quot;A100-SXM4-40GB&quot;, 8),
<font color="#859900">+    (&quot;GTX_1650_Ti_Max-Q&quot;, &quot;GeForce GTX 1650 Ti with Max-Q Design&quot;, 1),</font>
     (&quot;AGX_Xavier&quot;, &quot;Jetson-AGX&quot;, 1),
     (&quot;Xavier_NX&quot;, &quot;Xavier NX&quot;, 1)
 ])
</pre>

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ git diff closed/NVIDIA/configs/resnet50/Offline/config.json
<b>diff --git a/closed/NVIDIA/configs/resnet50/Offline/config.json b/closed/NVIDIA/configs/resnet50/Offline/config.json</b>
<b>index ea092358..da010128 100644</b>
<b>--- a/closed/NVIDIA/configs/resnet50/Offline/config.json</b>
<b>+++ b/closed/NVIDIA/configs/resnet50/Offline/config.json</b>
<font color="#2AA198">@@ -113,6 +113,23 @@</font>
         &quot;tensor_path&quot;: &quot;${PREPROCESSED_DATA_DIR}/imagenet/ResNet50/int8_linear&quot;,
         &quot;use_graphs&quot;: false
     },
<font color="#859900">+    &quot;GTX_1650_Ti_Max-Q&quot;: {</font>
<font color="#859900">+        &quot;config_ver&quot;: {</font>
<font color="#859900">+            &quot;triton&quot;: {</font>
<font color="#859900">+                &quot;use_triton&quot;: false</font>
<font color="#859900">+            }</font>
<font color="#859900">+        },</font>
<font color="#859900">+        &quot;gpu_batch_size&quot;: 128,</font>
<font color="#859900">+        &quot;gpu_copy_streams&quot;: 1,</font>
<font color="#859900">+        &quot;gpu_inference_streams&quot;: 1,</font>
<font color="#859900">+        &quot;gpu_offline_expected_qps&quot;: 500,</font>
<font color="#859900">+        &quot;input_dtype&quot;: &quot;int8&quot;,</font>
<font color="#859900">+        &quot;input_format&quot;: &quot;linear&quot;,</font>
<font color="#859900">+        &quot;map_path&quot;: &quot;data_maps/imagenet/val_map.txt&quot;,</font>
<font color="#859900">+        &quot;precision&quot;: &quot;int8&quot;,</font>
<font color="#859900">+        &quot;tensor_path&quot;: &quot;${PREPROCESSED_DATA_DIR}/imagenet/ResNet50/int8_linear&quot;,</font>
<font color="#859900">+        &quot;use_graphs&quot;: false</font>
<font color="#859900">+    },</font>
     &quot;T4x1&quot;: {
         &quot;config_ver&quot;: {
             &quot;triton&quot;: {
</pre>

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ git diff closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py
<b>diff --git a/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py b/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py</b>
<b>index 251e73b9..b8e24b4b 100644</b>
<b>--- a/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py</b>
<b>+++ b/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py</b>
<font color="#2AA198">@@ -87,7 +87,7 @@</font> class ResNet50(BenchmarkBuilder):
         # Query system id for architecture
         self.system_id = get_system_id()
         self.gpu_arch = None
<font color="#DC322F">-        if &quot;T4&quot; in self.system_id or &quot;TitanRTX&quot; in self.system_id:</font>
<font color="#859900">+        if self.system_id in [ &quot;GTX_1650_Ti_Max-Q&quot;, &quot;T4&quot;, &quot;TitanRTX&quot; ]:</font>
             self.gpu_arch = &quot;Turing&quot;
         elif &quot;V100&quot; in self.system_id or &quot;DGX-2H&quot; in self.system_id:
             self.gpu_arch = &quot;Volta&quot;
</pre>

Identifying the GTX 1650 Ti GPU as Turing enables the [full fusion plugin](https://github.com/mlcommons/inference_results_v0.7/blob/4b4331ac6586f3cfd23136cba5e92a0d94d4e44a/closed/NVIDIA/code/resnet50/tensorrt/res2_fusions.py#L332).

**Comment by psyhtest** [comment]
## Build and launch the Docker image

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~</b></font>$ 
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~</b></font>$ cd ~/projects/mlperf/submissions_inference_0_7/
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ make build_docker
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ docker image ls mlperf-inference
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mlperf-inference    anton               18c117db6cc2        2 weeks ago         15.4GB
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ export MLPERF_SCRATCH_PATH=/data/mlperf-scratch-path
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ make launch_docker
</pre>

## Build and run the ResNet50 Offline configuration

### Accuracy

<pre>(mlperf) anton@mlperf-inference-anton:/work$ make generate_engines RUN_ARGS=&quot;--benchmarks=resnet50 --scenarios=offline&quot; &amp;&amp; \
&gt; make run_harness RUN_ARGS=&quot;--benchmarks=resnet50 --scenarios=offline --test_mode=AccuracyOnly&quot;
...
accuracy=75.918%, good=37959, total=50000

======================= Perf harness results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Cannot find performance result. Maybe you are running in AccuracyOnly mode.


======================= Accuracy results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Accuracy = 75.918, Threshold = 75.695. Accuracy test PASSED.
</pre>

Note that with the full fusion plugin enabled, the accuracy dropped from 76.064% to 75.918%.

### Performance

<pre>(mlperf) anton@mlperf-inference-anton:/work$ make run_harness RUN_ARGS=&quot;--benchmarks=resnet50 --scenarios=offline --test_mode=PerformanceOnly&quot;
...
======================= Perf harness results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Samples per second: 396.688 and Result is : VALID


======================= Accuracy results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: No accuracy results in PerformanceOnly mode.
</pre>

**Comment by psyhtest** [comment]
## Prepare a new calibration cache

NVIDIA normally calibrate ResNet50 using [the official MLPerf option 1](https://github.com/mlperf/inference/blob/master/calibration/ImageNet/cal_image_list_option_1.txt).  We will calibrate ResNet50 using [the official MLPerf option 2](https://github.com/mlperf/inference/blob/master/calibration/ImageNet/cal_image_list_option_2.txt).

### Back up the original dataset and calibration map

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ cp build/data/imagenet{,.bak}
(mlperf) anton@mlperf-inference-anton:/work$ cp data_maps/imagenet/cal_map.txt{,.bak}
</pre>

### Prepare a calibration dataset using [Collective Knowledge](https://github.com/ctuning/ck)

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ python3 -m pip install ck --user
(mlperf) anton@mlperf-inference-anton:/work$ export PATH=~/.local/bin:$PATH
(mlperf) anton@mlperf-inference-anton:/work$ ck pull repo:ck-env
(mlperf) anton@mlperf-inference-anton:/work$ ck install package --tags=dataset,imagenet,aux
(mlperf) anton@mlperf-inference-anton:/work$ ck detect soft --tags=dataset,imagenet,val,original \
--search_dirs=/work/build/data
...
  Registering in the CK (/work/build/data/imagenet/ILSVRC2012_val_00000001.JPEG) ...

  Software entry found: dataset.imagenet.val (ff47fc6a33b4b03b)

Environment entry added (4149a4a0cc905062)!

(mlperf) anton@mlperf-inference-anton:/work$ ck pull repo:ck-openvino
(mlperf) anton@mlperf-inference-anton:/work$ ck install package --tags=dataset,imagenet,cal,mlperf.option2
...
Installation path: /home/anton/CK-TOOLS/dataset-imagenet-calibration-mlperf.option2
</pre>

### Prepare a new calibration cache

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ rm -rf build/data/imagenet && \
rm -rf build/preprocessed_data/imagenet/ResNet50/fp32 && \
cp -r $HOME/CK-TOOLS/dataset-imagenet-calibration-mlperf.option2 build/data/imagenet && \
cp build/data/imagenet/val_map.txt data_maps/imagenet/cal_map.txt && \
python3 code/resnet50/tensorrt/preprocess_data.py --cal_only && \
make calibrate RUN_ARGS="--benchmarks=resnet50"
</pre>

## Build and run the ResNet50 Offline configuration

### Accuracy

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ make generate_engines RUN_ARGS="--benchmarks=resnet50 --scenarios=offline" && \
make run_harness RUN_ARGS="--benchmarks=resnet50 --scenarios=offline --test_mode=AccuracyOnly"
...
accuracy=74.866%, good=37433, total=50000
Traceback (most recent call last):
  File "code/main.py", line 694, in <module>
    main(main_args, system_id)
  File "code/main.py", line 652, in main
    handle_run_harness(benchmark_conf, need_gpu, need_dla, profile, power)
  File "code/main.py", line 375, in handle_run_harness
    accuracy = check_accuracy(os.path.join(harness.get_full_log_dir(), "mlperf_log_accuracy.json"), config)
  File "code/main.py", line 502, in check_accuracy
    accuracy, threshold, accuracy_result))
RuntimeError: Accuracy = 74.866, Threshold = 75.695. Accuracy test FAILED!
Makefile:374: recipe for target 'run_harness' failed
make: *** [run_harness] Error 1
</pre>

With the full fusion plugin enabled, the accuracy dropped from 76.064% to 75.918%. With the full fusion plugin _and_ the new calibration cache enabled, the accuracy dropped from 76.064% to 74.866%, which is below the threshold.

### Performance

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ make run_harness RUN_ARGS="--benchmarks=resnet50 --scenarios=offline --test_mode=PerformanceOnly"
...
======================= Perf harness results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Samples per second: 391.154 and Result is : VALID


======================= Accuracy results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: No accuracy results in PerformanceOnly mode.
</pre>

**Comment by psyhtest** [comment]
Note that despite the GTX 1650 Ti being a Turing GPU, the full fusion plugin is not beneficial performance-wise.

## Disable the plugin (restore `ResNet50.py`)

<pre><font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ git diff closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py                                                                                          
<b>diff --git a/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py b/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py</b>                                                                                           
<b>index 251e73b9..b8e24b4b 100644</b>                                                                      
<b>--- a/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py</b>                                               
<b>+++ b/closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py</b>                                               
<font color="#2AA198">@@ -87,7 +87,7 @@</font> class ResNet50(BenchmarkBuilder):                                                  
         # Query system id for architecture
         self.system_id = get_system_id()                                                            
         self.gpu_arch = None 
<font color="#DC322F">-        if &quot;T4&quot; in self.system_id or &quot;TitanRTX&quot; in self.system_id:</font>                                  
<font color="#859900">+        if self.system_id in [ &quot;GTX_1650_Ti_Max-Q&quot;, &quot;T4&quot;, &quot;TitanRTX&quot; ]:</font>                             
             self.gpu_arch = &quot;Turing&quot;
         elif &quot;V100&quot; in self.system_id or &quot;DGX-2H&quot; in self.system_id:                                
             self.gpu_arch = &quot;Volta&quot;
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ git checkout -- closed/NVIDIA/code/resnet50/tensorrt/ResNet50.py                                                                                   
<font color="#859900"><b>anton@krai</b></font>:<font color="#268BD2"><b>~/projects/mlperf/submissions_inference_0_7</b></font>$ git diff   </pre>

## Re-build and run the ResNet50 Offline configuration

### Accuracy

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ make generate_engines RUN_ARGS="--benchmarks=resnet50 --scenarios=offline" && \
make run_harness RUN_ARGS="--benchmarks=resnet50 --scenarios=offline --test_mode=AccuracyOnly"
...
======================= Perf harness results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Cannot find performance result. Maybe you are running in AccuracyOnly mode.


======================= Accuracy results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Accuracy = 76.062, Threshold = 75.695. Accuracy test PASSED.
</pre>

With the new calibration cache only, the accuracy dropped from 76.064% to 76.062%, or just by 1 mispredicted image. This is completely expected, as both 500 image calibration datasets were drawn randomly. (For comparison, [the difference with OpenVINO](https://github.com/ctuning/ck-env/blob/master/package/dataset-imagenet-calibration/README.md) was 0.106% or 53 images.)

### Performance

<pre>
(mlperf) anton@mlperf-inference-anton:/work$ make run_harness RUN_ARGS="--benchmarks=resnet50 --scenarios=offline --test_mode=PerformanceOnly"
...
======================= Perf harness results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: Samples per second: 483.397 and Result is : VALID


======================= Accuracy results: =======================

GTX_1650_Ti_Max-Q_TRT-default-Offline:
    resnet50: No accuracy results in PerformanceOnly mode.
</pre>

With the full fusion plugin disabled, the performance increased from 396 samples per second to 483 samples per second, up by 22%.

The plugin could have been beneficial, however, on [DellEMC's Quadro RTX powered systems](https://github.com/mlcommons/inference_results_v0.7/blob/master/closed/DellEMC/code/common/system_list.py), but given [the accuracy results](https://github.com/mlcommons/inference_results_v0.7/issues/9#issuecomment-726908354) was likely disabled for their v0.7 submission.

**Comment by nvpohanh** [comment]
The accuracy drop is caused by a typo bug inside TensorRT 7.2 release source code.

With the bug, the "**res2c_br2a**" layer would mistakenly use the scale of "**res2c_relu_out_0**", instead of the correct "**res2b_relu_out_0**" scale, as its input scale. This effectively scales the input activations to the "**res2c_br2a**" layer by `(res2c_relu_out_0 / res2b_relu_out_0)` and causes accuracy drop, without any performance difference.

The accuracy drop didn't manifest itself in our submission since the values of "**res2b_relu_out_0**" scale and the "**res2c_branch2c_out_0**" scale are closer in our original calibration cache, whereas with new calibration set, they are more different:
- original cache:
  - res2b_relu_out_0: 0.0909325554967
  - res2c_relu_out_0: 0.0766444727778
  - res2b_relu_out_0 / res2c_relu_out_0: 1.1864202623
- Anton's new cache:
  - res2b_relu_out_0: 0.0626606568694
  - res2c_relu_out_0: 0.086742118001
  - res2b_relu_out_0 / res2c_relu_out_0: 0.72237868193

We have fixed this typo bug on our side and it will be fixed in the following TensorRT release.

**Comment by psyhtest** [comment]
Thank you for confirming @nvpohanh! Closing the issue.
